### ISSUE TITLE
Heroku support

### ISSUE THREAD

**Issue by ghost** [neoid-gem/neoid#12]
Wondering if you have any thoughts regarding replacing the gremlin parts of Neoid with the equivalent non-gremlin Neography calls. It seems like this should be possible, but I don't know if there might be reasons (performance?) not to do so.

**Comment by elado** [comment]
When I started this gem Heroku had Gremlin support. It's a shame they've removed it, but fortunately the app I was working on still runs on the old Neo4j plan with Gremlin. Right now I'm in the process of migrating to new servers so I'll have Gremlin anyway.

Gremlin is used because one script of upsert is faster than two/three REST calls. I may have to extract the communication to different providers so it can use gremlin as default and fallback to REST when gremlin is not supported.
I do think this is really important to be able to support Heroku.

Right now I have a bunch of code revamp that I'm still testing so it'll be hard to manage pull requests, I hope to get to that after next version release.

**Comment by elado** [comment]
Now that the latest release is live, PRs are welcome.
The problems I see will be using batches, because right now the batch executes a full script that contains both query, and update or insert.
Using REST only would make those separate dependent calls.

**Comment by albertoperdomo** [comment]
Hi, I'm one of the founders of [GrapheneDB](http://www.graphenedb.com), a Neo4j as a service platform. When we launched the private beta of our service we didn't support Gremlin like Heroku, but we do now.

We've just moved to a public beta and we offer a free plan, which is similar to the Heroku addon, except we do support and Gremlin and are about to launch new features like a community repo of plugins and server extensions and the possibility of running your own.

We also offer the latest versions of Neo4j plus the milestone releases.

We even have customers running apps in production on our dedicated offering using neoid.

It'd be awesome if you guys could give it a try, give us feedback and perhaps put a note in your README, where you currently tell people the best option is to run their own instances.

Please let me what you think.

Cheers!

**Comment by albertoperdomo** [comment]
Ping @elado

**Comment by BenMorganIO** [comment]
Will place a note in the readme that GrapheneDB on Heroku does support Gremlin.

@albertoperdomo, I will still proceed to fix Issue #39 and the note will then be removed.
